version: '3.8'

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    environment:
      - SHARED_DIRECTORY=/nfsshare
    volumes:
      - /home/nfsserver/data:/nfsshare  # Mount a local directory as the NFS share
    ports:
      - "2049:2049"  # NFS port
    networks:
      - nfs-network
    restart: always

networks:
  nfs-network:
    driver: bridge
