/*!999999\- enable the sandbox mode */ 
INSERT INTO `cluster_component_datasource_map_master` VALUES
(113,'bulk','dn_payload'),
(116,'bulk','smpp_concat'),
(1,'common','account_sync'),
(30,'common','capping_chk'),
(15,'common','dlr_wait_retry'),
(10,'common','duplicate_chk'),
(12,'common','duplicate_dn'),
(6,'common','http_dlr_handover'),
(7,'common','intrim_dlr'),
(2,'common','kafka_service'),
(3,'common','kannel_redis'),
(4,'common','messageid_generator'),
(9,'common','pri_dnd_chk'),
(5,'common','shortcode_provider'),
(21,'common','smpp_client_dn'),
(27,'common','smpp_consumer'),
(29,'common','smpp_session'),
(8,'common','timebound_chk'),
(20,'common','wallet_chk'),
(313,'intl','dn_payload'),
(316,'intl','smpp_concat'),
(213,'otp','dn_payload'),
(216,'otp','smpp_concat'),
(13,'trans','dn_payload'),
(16,'trans','smpp_concat');
