cd subt2tb/all/
docker-compose down
cd ../..
cd dnt2tb/all/
docker-compose down
cd ../..
cd dnt2tbbkup/all/
docker-compose down
cd ../..
cd dnp/all/
docker-compose down
cd ../..
cd dnpostlogt2tb/all/
docker-compose down
cd ../..
cd dnnopayloadt2tb/all/
docker-compose down
cd ../..
cd errorlogt2tb/all/
docker-compose down
cd ../..
cd fullmsg/all/
docker-compose down
cd ../..
cd t2e/all/
docker-compose down
cd ../..
cd clienthandovert2tb/all/
docker-compose down
cd ../..

