version: '3'
services:
  api:
    image: dockerregistry:5000/node-cmjobs:31dec2024
    ports:
      - "3001:3001"
    volumes: ['./logs:/usr/src/app/log','./.env:/usr/src/app/.env','/home/data/fileprocessor:/fileprocessordata']
    restart: always
    networks:
      - uibackendnetwork
networks:
  uibackendnetwork:
    external: true
 
