version: '3.8'

services:
  subk2es:
    image: dockerregistry:5000/beacon:18dec2024
    volumes:
      - './config/kafka2es_sub.properties:/kafka2es.properties'
      - './logs:/opt/jboss/wildfly/logs' 
    environment: [module=k2es,profile=do3,appmode=deliveries,priority=$PRIORITY,threadcount=1,topicgroupid=2]
