version: '3.8'

services:
  logprocessor:
    image: dockerregistry:5000/fileprocessorsingleton:31dec2024
    volumes:
      - './logs:/opt/jboss/wildfly/logs'
      - './tomcatlog:/opt/tomcat/logs' 
      - './config/logging.properties:/opt/tomcat/conf/logging.properties'
      - '/home/data/fileprocessor:/fileprocessordata' 
    environment:
      - profile=do2
      - propertyip=224  
    networks:
      - uibackendnetwork
networks:
  uibackendnetwork:
    external: true
