services:
  poller:
    image: 10.122.0.2:5000/beacon:17nov2024
    environment: [module=dnfp,profile=do1,modvalue=$MOD,id=1,dlrpayloadgen.cluster=$CLUSTER ]
    volumes: ['./logs:/opt/jboss/wildfly/logs']
version: '3'
