services:
  ic:
    image: dockerregistry:5000/beacon:31dec2024
    environment: [
       id=1, _JAVA_OPTIONS=-Xmx1g -Xms512m,module=smppconcatehandover,hostname=10.122.0.10,segment=ch5,profile=do2,priority=$PRIORITY,dlrpayloadgen.cluster=$CLUSTER,modvalue=$MOD,cluster.names=$CLUSTER,handovergw=unitia]
    volumes: ['./logs:/opt/jboss/wildfly/logs']
    restart: always
    logging:
      driver: "none"
    networks:
      - concate
networks:
  concate:
    external: true
version: '3'
