cd dlrpayloaddngenerator/
docker-compose down
cd ..
cd ac/all/
docker-compose down
cd ../..
cd dnpost/http/all/
docker-compose down
cd ../../..
cd dnpost/smpp/all/
docker-compose down
cd ../../..
cd dnpost/smpp/poller/
docker-compose down
cd ../../..
cd duplicatecheckcleanup/
docker-compose down
cd ..
cd kannelstatusupdator/
docker-compose down
cd ..
cd poller/dnfp/
docker-compose down
cd ../..
cd poller/ifp/
docker-compose down
cd ../..
cd poller/scheduleblockoutpoller/
docker-compose down
cd ../..
cd smppconcatehandover/
docker-compose down
cd ..
cd rc/all/
docker-compose down
cd ../..
