version: '3.8'

services:
  logprocessor:
    image: dockerregistry:5000/queryprocesor:11jan2025
    volumes:
      - './logs:/opt/jboss/wildfly/logs'
      - '/home/data/fileprocessor/log_download/csv:/csv'
      - '/home/data/sqlite:/sqlite'
      - './config/log4j2-common.xml:/log4j2-common.xml'
    environment:
      - module=qptp
      - profile=do1
    networks:
      - uibackendnetwork
networks:
  uibackendnetwork:
    external: true

