version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://10.139.244.160:31200
    ports:
      - "5601:5601"
