CREATE SCHEMA config
  AUTHORIZATION appuser;

CREATE SCHEMA summary
  AUTHORIZATION appuser;

CREATE SCHEMA smslog
  AUTHORIZATION appuser;
  
CREATE SCHEMA stage
  AUTHORIZATION appuser;

GRANT USAGE ON SCHEMA config TO rptuser;
GRANT USAGE ON SCHEMA summary TO rptuser;
GRANT USAGE ON SCHEMA smslog TO rptuser;
GRANT USAGE ON SCHEMA stage TO rptuser;


GRANT SELECT ON ALL TABLES IN SCHEMA config TO rptuser;
GRANT SELECT ON ALL TABLES IN SCHEMA summary TO rptuser;
GRANT SELECT ON ALL TABLES IN SCHEMA smslog TO rptuser;
GRANT SELECT ON ALL TABLES IN SCHEMA stage TO rptuser;
