-- DROP TABLE stage.deliveries;
-- DROP TABLE stage.full_message;
-- DROP TABLE stage.submission;


CREATE TABLE stage.deliveries (
	cli_id numeric(19) NOT NULL,
	platform_cluster varchar(10) NOT NULL,
	sms_priority numeric(1) NOT NULL,
	dn_hdr varchar(15) DEFAULT NULL::character varying NULL,
	dest numeric(19) DEFAULT NULL::numeric NULL,
	base_msg_id varchar(25) NOT NULL,
	msg_id varchar(25) NOT NULL,
	msg_id_seq numeric(3) NOT NULL,
	file_id varchar(25) DEFAULT NULL::character varying NULL,
	recv_time timestamp(6) NOT NULL,
	recv_date date NOT NULL,
	act_recv_time timestamp NOT NULL,
	act_recv_date date NOT NULL,
	carrier_datetime_format varchar(15) DEFAULT NULL::character varying NULL,
	msg_part_no numeric(3) DEFAULT NULL::numeric NULL,
	total_msg_parts numeric(3) DEFAULT NULL::numeric NULL,
	retry_attempt numeric(1) DEFAULT NULL::numeric NULL,
	act_route_id varchar(6) DEFAULT NULL::character varying NULL,
	dlr_from_internal numeric(1) DEFAULT NULL::numeric NULL,
	route_logic_id varchar(3) DEFAULT NULL::character varying NULL,
	route_id varchar(6) DEFAULT NULL::character varying NULL,
	smsc_id varchar(20) DEFAULT NULL::character varying NULL,
	carrier_full_dn varchar(2000) DEFAULT NULL::character varying NULL,
	dly_time timestamp NULL,
	act_dly_time timestamp NULL,
	carrier_rcvd_time timestamp NULL,
	carrier_ack_id varchar(100) DEFAULT NULL::character varying NULL,
	carrier_sys_id varchar(20) DEFAULT NULL::character varying NULL,
	term_carrier varchar(200) DEFAULT NULL::character varying NULL,
	term_circle varchar(200) DEFAULT NULL::character varying NULL,
	delv_lat_ori_in_millis numeric(19) DEFAULT NULL::numeric NULL,
	delv_lat_sla_in_millis numeric(19) DEFAULT NULL::numeric NULL,
	overall_lat_in_millis numeric(19) DEFAULT NULL::numeric NULL,
	dlr_type numeric(1) DEFAULT NULL::numeric NULL,
	dn_ori_sts_code varchar(5) NOT NULL,
	dn_cli_sts_code varchar(5) NOT NULL,
	dn_ori_sts_desc varchar(100) NOT NULL,
	dn_cli_sts_desc varchar(100) NOT NULL,
	car_ori_sts_code varchar(5) DEFAULT NULL::character varying NULL,
	car_ori_sts_desc varchar(10) DEFAULT NULL::character varying NULL,
	car_sts_code varchar(100) DEFAULT NULL::character varying NULL,
	car_sts_desc varchar(100) DEFAULT NULL::character varying NULL,
	retry_ori_route_id varchar(6) DEFAULT NULL::character varying NULL,
	retry_alt_route_id varchar(6) DEFAULT NULL::character varying NULL,
	delivery_status varchar(10) DEFAULT NULL::character varying NULL,
	car_delivery_status varchar(10) DEFAULT NULL::character varying NULL,
	sms_rate numeric(10, 4) DEFAULT 0.0 NOT NULL,
	dlt_rate numeric(10, 4) DEFAULT 0.0 NOT NULL,
	created_ts timestamp NOT NULL,
	pg_created_ts timestamp DEFAULT now() NULL,
	billing_sms_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	billing_add_fixed_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	base_sms_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	base_add_fixed_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	ref_sms_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	ref_add_fixed_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	CONSTRAINT deliveries_pk PRIMARY KEY (recv_date, msg_id, msg_id_seq)
)
PARTITION BY LIST (recv_date);
CREATE INDEX deliveries_bmsg_id ON ONLY stage.deliveries USING btree (base_msg_id);
CREATE INDEX deliveries_cli_id ON ONLY stage.deliveries USING btree (cli_id);
CREATE INDEX deliveries_dest ON ONLY stage.deliveries USING btree (dest);
CREATE INDEX deliveries_rcv_tm ON ONLY stage.deliveries USING btree (recv_time);


CREATE TABLE stage.full_message (
	cli_id numeric(19) NOT NULL,
	recv_date date NOT NULL,
	base_msg_id varchar(25) NOT NULL,
	base_msg_id_seq numeric(3) NOT NULL,
	long_msg text NULL,
	created_ts timestamp NULL,
	pg_created_ts timestamp DEFAULT now() NULL,
	encrypted_long_msg text NULL,
	CONSTRAINT full_message_pk PRIMARY KEY (recv_date, base_msg_id, base_msg_id_seq)
)
PARTITION BY LIST (recv_date);
CREATE INDEX full_message_bmsg_id ON ONLY stage.full_message USING btree (base_msg_id);
CREATE INDEX full_message_cli_id ON ONLY stage.full_message USING btree (cli_id);


CREATE TABLE stage.submission (
	intf_type varchar(10) NOT NULL,
	intf_grp_type varchar(10) NOT NULL,
	msg_source varchar(25) NOT NULL,
	intl_msg numeric(1) NOT NULL,
	cli_id numeric(19) NOT NULL,
	msg_type numeric(1) NOT NULL,
	platform_cluster varchar(10) NOT NULL,
	sms_priority numeric(1) NOT NULL,
	bill_encrypt_type numeric(1) NOT NULL,
	bill_type numeric(1) NOT NULL,
	app_type varchar(10) NOT NULL,
	msg text NULL,
	udhi numeric(1) DEFAULT NULL::numeric NULL,
	udh varchar(15) DEFAULT NULL::character varying NULL,
	dcs varchar(3) DEFAULT NULL::character varying NULL,
	hdr varchar(15) DEFAULT NULL::character varying NULL,
	dest numeric(19) DEFAULT NULL::numeric NULL,
	msg_id varchar(25) NOT NULL,
	msg_id_seq numeric(3) NOT NULL,
	file_id varchar(25) DEFAULT NULL::character varying NULL,
	base_msg_id varchar(25) NOT NULL,
	cli_msg_id varchar(50) DEFAULT NULL::character varying NULL,
	recv_time timestamp NOT NULL,
	recv_date date NOT NULL,
	act_recv_time timestamp NOT NULL,
	act_recv_date date NOT NULL,
	cli_max_split numeric(2) DEFAULT '0'::numeric NULL,
	msg_tag varchar(50) DEFAULT NULL::character varying NULL,
	is_hex_msg numeric(1) DEFAULT '0'::numeric NULL,
	max_validity_in_sec numeric(10) DEFAULT NULL::numeric NULL,
	cli_ip varchar(30) NOT NULL,
	msg_class varchar(5) DEFAULT NULL::character varying NULL,
	country varchar(20) DEFAULT NULL::character varying NULL,
	param1 varchar(50) DEFAULT NULL::character varying NULL,
	param2 varchar(50) DEFAULT NULL::character varying NULL,
	param3 varchar(50) DEFAULT NULL::character varying NULL,
	param4 varchar(50) DEFAULT NULL::character varying NULL,
	param5 varchar(50) DEFAULT NULL::character varying NULL,
	param6 varchar(100) DEFAULT NULL::character varying NULL,
	param7 varchar(100) DEFAULT NULL::character varying NULL,
	param8 varchar(100) DEFAULT NULL::character varying NULL,
	param9 varchar(250) DEFAULT NULL::character varying NULL,
	param10 varchar(500) DEFAULT NULL::character varying NULL,
	sch_date_time timestamp NULL,
	cli_dlt_tmpl_id numeric(19) DEFAULT NULL::numeric NULL,
	dlt_tmpl_id numeric(19) DEFAULT NULL::numeric NULL,
	cli_dlt_entity_id numeric(19) DEFAULT NULL::numeric NULL,
	dlt_entity_id numeric(19) DEFAULT NULL::numeric NULL,
	app_ins_id varchar(5) DEFAULT NULL::character varying NULL,
	blkout_type varchar(10) DEFAULT NULL::character varying NULL,
	msg_part_no numeric(3) DEFAULT NULL::numeric NULL,
	total_msg_parts numeric(3) DEFAULT NULL::numeric NULL,
	feature_code varchar(5) DEFAULT NULL::character varying NULL,
	cli_tmpl_id numeric(19) DEFAULT NULL::numeric NULL,
	retry_attempt numeric(1) DEFAULT NULL::numeric NULL,
	shortner_id varchar(100) DEFAULT NULL::character varying NULL,
	msg_shortned numeric(1) DEFAULT NULL::numeric NULL,
	route_id varchar(6) DEFAULT NULL::character varying NULL,
	act_route_id varchar(6) DEFAULT NULL::character varying NULL,
	circle varchar(200) DEFAULT NULL::character varying NULL,
	carrier varchar(200) DEFAULT NULL::character varying NULL,
	carrier_sub_time timestamp NULL,
	act_carrier_sub_time timestamp NULL,
	aplha_value varchar(15) DEFAULT NULL::character varying NULL,
	cli_hdr varchar(15) DEFAULT NULL::character varying NULL,
	intf_country_code varchar(5) DEFAULT NULL::character varying NULL,
	route_logic_id varchar(3) DEFAULT NULL::character varying NULL,
	masked_hdr varchar(15) DEFAULT NULL::character varying NULL,
	smsc_id varchar(20) DEFAULT NULL::character varying NULL,
	dlr_type numeric(1) DEFAULT NULL::numeric NULL,
	encrypted_msg text NULL,
	encrypted_dest varchar(100) DEFAULT NULL::character varying NULL,
	sub_lat_ori_in_millis numeric(19) DEFAULT NULL::numeric NULL,
	sub_lat_sla_in_millis numeric(19) DEFAULT NULL::numeric NULL,
	file_name varchar(500) DEFAULT NULL::character varying NULL,
	campaign_id varchar(36) DEFAULT NULL::character varying NULL,
	campaign_name varchar(50) DEFAULT NULL::character varying NULL,
	msg_tag1 varchar(50) DEFAULT NULL::character varying NULL,
	msg_tag2 varchar(50) DEFAULT NULL::character varying NULL,
	msg_tag3 varchar(50) DEFAULT NULL::character varying NULL,
	msg_tag4 varchar(50) DEFAULT NULL::character varying NULL,
	msg_tag5 varchar(50) DEFAULT NULL::character varying NULL,
	sub_ori_sts_code varchar(5) NOT NULL,
	sub_cli_sts_code varchar(5) NOT NULL,
	sub_ori_sts_desc varchar(100) NOT NULL,
	sub_cli_sts_desc varchar(100) NOT NULL,
	sub_status varchar(10) DEFAULT NULL::character varying NULL,
	sms_rate numeric(10, 4) DEFAULT 0.0 NOT NULL,
	dlt_rate numeric(10, 4) DEFAULT 0.0 NOT NULL,
	add_error_info text NULL,
	created_ts timestamp NOT NULL,
	pg_created_ts timestamp DEFAULT now() NULL,
	billing_currency varchar(3) NULL,
	billing_sms_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	billing_add_fixed_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	base_currency varchar(5) NULL,
	base_sms_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	base_add_fixed_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	ref_currency varchar(5) NULL,
	ref_sms_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	ref_add_fixed_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	billing_exchange_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	ref_exchange_rate numeric(16, 12) DEFAULT 0.000000 NOT NULL,
	smpp_recv_time timestamp NULL,
	mcc varchar(10) NULL,
	mnc varchar(10) NULL,
	segment varchar(25) NULL,
	CONSTRAINT submission_pk PRIMARY KEY (recv_date, msg_id, msg_id_seq)
)
PARTITION BY LIST (recv_date);
CREATE INDEX submission_bmsg_id ON ONLY stage.submission USING btree (base_msg_id);
CREATE INDEX submission_cli_id ON ONLY stage.submission USING btree (cli_id);
CREATE INDEX submission_dest ON ONLY stage.submission USING btree (dest);
CREATE INDEX submission_rcv_tm ON ONLY stage.submission USING btree (recv_time);